spring.config.import=optional:file:.env[.properties]

spring.application.name=api-gateway
server.port=8080

# JWT
app.jwt.secret=${JWT_SECRET}

# Rutas hacia MS-Usuarios
spring.cloud.gateway.server.webflux.routes[0].id=ms-usuarios
spring.cloud.gateway.server.webflux.routes[0].uri=${MS_USUARIOS_URL}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**,/api/usuarios/**