spring.config.import=optional:file:.env[.properties]

spring.application.name=api-gateway
server.port=8080

# JWT
app.jwt.secret=${JWT_SECRET}

# Rutas hacia MS-Usuarios
spring.cloud.gateway.server.webflux.routes[0].id=ms-usuarios
spring.cloud.gateway.server.webflux.routes[0].uri=${MS_USUARIOS_URL}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**,/api/usuarios/**

# Rutas hacia MS-Productos
spring.cloud.gateway.server.webflux.routes[1].id=ms-productos
spring.cloud.gateway.server.webflux.routes[1].uri=${MS_PRODUCTOS_URL}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/productos/**

spring.cloud.gateway.server.webflux.routes[2].id=ms-compras
spring.cloud.gateway.server.webflux.routes[2].uri=${MS_COMPRAS_URL}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/pedidos/**

# CORS - permitir peticiones desde el frontend
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOriginPatterns=http://localhost:*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true